/**
 * Quiz Models - TypeScript interfaces matching backend schemas
 * These models mirror the Pydantic schemas in app/schemas/quizzes.py
 */

// ========================
// Quiz Question Model
// ========================
/**
 * Represents a single MCQ question inside a quiz.
 * Maps to backend QuizQuestion schema.
 */
export interface QuizQuestion {
  question: string;       // The question text
  options: string[];      // 2-4 options for MCQ
  answer: string;         // The correct answer (must match one option)
}

// ========================
// Quiz Create Payload
// ========================
/**
 * Payload for creating a new quiz (sent to POST /quizzes/).
 * Maps to backend QuizCreate schema.
 */
export interface QuizCreate {
  courseId: string;           // MongoDB ObjectId of the course
  courseName: string;         // Name of the course (for display)
  teacherId: string;          // MongoDB ObjectId of the teacher
  tenantId: string;           // MongoDB ObjectId of the tenant
  quizNumber: number;         // Quiz number (>= 1)
  description?: string;       // Optional description
  dueDate: string;            // ISO date string
  questions: QuizQuestion[];  // List of MCQ questions
  timeLimitMinutes?: number;  // Optional time limit in minutes
  totalMarks: number;         // Total marks for the quiz
  aiGenerated?: boolean;      // Whether generated by AI
}

// ========================
// Quiz Update Payload
// ========================
/**
 * Payload for updating an existing quiz (sent to PATCH /quizzes/{id}).
 * All fields are optional - only send what you want to update.
 * Maps to backend QuizUpdate schema.
 */
export interface QuizUpdate {
  quizNumber?: number;
  description?: string;
  dueDate?: string;
  questions?: QuizQuestion[];
  timeLimitMinutes?: number;
  totalMarks?: number;
  aiGenerated?: boolean;
  status?: 'active' | 'inactive';
}

// ========================
// Quiz Response Model
// ========================
/**
 * Response returned from backend after create/get/update operations.
 * Maps to backend QuizResponse schema.
 */
export interface Quiz {
  id: string;                   // MongoDB ObjectId as string
  courseId: string;
  courseName: string;
  teacherId: string;
  tenantId: string;
  quizNumber: number;
  description?: string;
  dueDate: string;              // ISO date string from backend
  questions: QuizQuestion[];
  timeLimitMinutes?: number;
  totalMarks: number;
  aiGenerated: boolean;
  status: 'active' | 'inactive';
  createdAt: string;            // ISO date string
  updatedAt?: string;           // ISO date string (optional)
}

// ========================
// Quiz List Query Params
// ========================
/**
 * Query parameters for filtering quizzes (GET /quizzes/).
 */
export interface QuizListParams {
  tenant_id?: string;
  teacher_id?: string;
  course_id?: string;
  search?: string;
  sort?: string;        // 'createdAt' or '-createdAt'
  page?: number;
  limit?: number;
}
